version: '3.8'

services:
  manim-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3